### ISSUE TITLE
add UTF header for Chinese

### ISSUE THREAD

**Issue by tigerneil** [percyliang/sfig#19]
sfig is cool. 
I try to write slides in Chinese. But I find Chinese word can't show out properly. 
I use enca check the encoding of `index.html`,  it is ascii.
So I add `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />` in the header.
We can add this line to header to support CJK. 
Glad to see other gentle and neat solution.

**Comment by percyliang** [comment]
Great.  Added that meta line to the `create-presentation` script.
